### PR TITLE
Build warning fix and autotools conversion

### PR DESCRIPTION
**Pull request by jtlayton**
Ok, respun pull request...

This adds a minor patch to fix a build warning that pops up on recent gcc, and adds some autoconf magic to convert spooky-c.c into shared and static libs, suitable for packaging on distros.

I imagine that the first patch is almost certainly OK. Let me know about the second one though. If you have a strong objection to use autotools here, we can drop it and I'll just maintain it for the Fedora package.

Thanks!

### CODE REVIEW

**Comment by andikleen** [comment]
I'm not a big fan of autoconf, but if it makes a packager's life easier that's ok.

But please remove the -Werror. Nothing ever should ship with -Werror.

**Comment by jtlayton** [comment]
Done. I've also added an autoconf test to check for unaligned access requirements, instead of relying on the arch macros provided by the compiler.

**Comment by andikleen** [comment]
-#if defined(__i386__) || defined(__x86_64__) // add more architectures here
+#ifndef HAVE_ALIGNED_ACCESS_REQUIRED

Could you keep the existing architectures in the ifdef, so that it still works fast on x86 without a config.h?

**Comment by jtlayton** [comment]
Sure. How's this?

**Comment by andikleen** [comment]
Merged thanks.

**Pull request merged**
